project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bourbonut
      - icon: linkedin
        href: https://www.linkedin.com/in/benjamin-bourbon/
    left:
      - text: "Posts"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
  page-footer: "Copyright 2023, Bourbon Benjamin"

format:
  html:
    theme: [cerulean, theme.scss]
    highlight-style: syntax.theme

