project:
  type: website

website:
  title: "Blog"
  site-url: "https://bourbonut.github.io/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bourbonut
      - icon: linkedin
        href: https://www.linkedin.com/in/benjamin-bourbon/
    left:
      - text: "Posts"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
  page-footer: "Copyright 2023-2025, Bourbon Benjamin"
  repo-url: https://github.com/bourbonut/bourbonut.github.io
  repo-actions: [source, issue]

format:
  html:
    theme: [cerulean, theme.scss]
    highlight-style: syntax.json
